pipeline {
    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }

    stages {
        stage('Checkout from GitHub') {
            steps {
                sh '''
                    git clone https://intranetdbhub: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@github.com/intranetdbhub/.net.git
                    cd .net/Projects/csr-secure-pipeline
                '''
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                sh '''
                    cd .net/Projects/csr-secure-pipeline
                    ansible-playbook -i inventory/inventory.ini playbooks/run_cisco_commands.yml \
                      -e ansible_user=ec2-user -e ansible_password=cisco
                '''
            }
        }
    }
}

