---
- name: Connect to Cisco CSR1000V and run commands
  hosts: cisco_csr
  gather_facts: no

  tasks:
    - name: Show version
      ios_command:
        commands:
          - show version

    - name: Show running config
      ios_command:
        commands:
          - show running-config | section hostname
          - show running-config | section interface

