---
- name: Connect to Cisco CSR1000V and run commands
  hosts: csr1
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Shutdown Loopback10
      ios_config:
        lines:
          - shutdown
        parents: interface Loopback10


