services:
  mongodb:
    image: mongo:7
    container_name: aurcoste001a-mdb001a
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: aurcoste001a-mex001a
    ports:
      - "6080:8081" 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - mongo-net

volumes:
  mongo-data:

networks:
  mongo-net:
