services:
  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: cisco
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextclouduser
      MYSQL_PASSWORD: cisco
    volumes:
      - nextcloud-db:/var/lib/mysql

  app:
    image: nextcloud
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      MYSQL_PASSWORD: cisco
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextclouduser
      MYSQL_HOST: db
    volumes:
      - nextcloud-data:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nextcloud_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: cisco
    depends_on:
      - db

volumes:
  nextcloud-db:
  nextcloud-data: