all:
  children:
    cisco_devices:
      hosts:
        AURCOSTE001A-CSR001:
          ansible_host: 10.68.2.10
        AURCOSTE001A-CSS001A:
          ansible_host: 10.68.1.2
      vars:
        ansible_connection: network_cli
        ansible_network_os: cisco.ios.ios
        ansible_user: admin
        ansible_password: cisco
